### create user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Bagus Dwi",
    "email": "ghoostdwi@gmail.com",
    "password": "123456"
}

### Login User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "ghoostdwi@gmail.com",
    "password": "123456"
}

### login token
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkJhZ3VzIER3aSIsImVtYWlsIjoic3VnYWIuZHdpODhAZ21haWwuY29tIiwiaWF0IjoxNzE1NzY1ODY1fQ.IRPCLZZP0EOmctU_4T03eAsoyQ6rnknt_Y5GFodPuDA

### Get all user
GET http://localhost:3000/api/v1/users

### Get all user by search
GET http://localhost:3000/api/v1/users?search=bagus

